### ISSUE TITLE
1.5 Create a Use Case Diagram

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#1]
Task title ID: #1.5
Task description: Develop the Use Case diagram that covers all the requirements
Goal: Complete the use case diagram, covering all requirements
Success criteria: The use case covers all requirements
Allocated time: 3 days
Start date: 05/09/2023
End date: 07/09/2023
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by Darius-Lim-zh** [comment]
Use Case Diagram completed
Closed on 12/9/2023

**Comment by jayfey** [comment]
Use Case Diagram completed
Closed on 13/9/2023
