### ISSUE TITLE
1.3.2 Prepare presentation for M1

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#14]
Task title ID: #1.3.2
Task description: Prepare the presentation for M1
Goal: Have presentation slides that covers the scope of M1
Success criteria: All deliverables are covered
Allocated time: 1 week
Start date: 19/9/2023
End date: 25/9/2023
Owner: Zhen Yu
Status: Completed
Priority: High

**Comment by 2200877** [comment]
Work Done description: Presentation completed
Work committed to repo: No work committed to the repo

How does this work affect other work: Presentation done

Start/End date: Started on 19/09/2023, ended on 25/09/2023
