### ISSUE TITLE
1.12 Explore technologies

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#16]
Task title ID: #1.12
Task description: Explore what technologies will be best to meet the requirements
Goal: Find the appropriate technologies to meet requirements
Success criteria: All necessary technologies are found
Allocated time: 7 days
Start date: 29 August 2023
End date: 4 September 2023
Owner: Zhen Yu
Status:  Completed
Priority: High

**Comment by 2200877** [comment]
1. Explored existing technologies for the software
2. No commits
3. Does not affect other work
4. Started 29/08/23, Ended 19/09/23. Severely underestimated timing for this, and was actively looking into it up till now.
