### ISSUE TITLE
1.2 Analyse requirements

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#17]
Task title ID: #1.2
Task description: Analyze the initial requirements given in the project description and analyze the additional requirements by the client after the meeting
Goal: Get a clear idea of all requirements needed
Success criteria: All requirements are gathered from the client
Allocated time:  3 weeks
Start date: 29/8/2023
End date: 15/9/2023
Owner: Ryan
Status: Completed
Priority: High

**Comment by LEEKWRYAN** [comment]
Sent 2 follow-up emails containing details of first meeting to validate requirements, and included additional questions that were not able to be asked due to time constraints of the first meeting. Awaiting for client's reply.
Started on 6/9/2023

**Comment by LEEKWRYAN** [comment]
Client replied to the follow-up email on 13/9/2023
Refined the requirements analysis based on client's feedback, thus completing this task on  15/9/2023
