### ISSUE TITLE
1.6 Write Use Case Description

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#18]
Task title ID: #1.6
Task description: Write the use case description for each use case
Goal: Fill all use case descriptions
Success criteria: All use case are filled and covers the requirements given
Allocated time: 3 days
Start date: 05/09/2023
End date: 07/09/2023
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by Darius-Lim-zh** [comment]
Use Case Description completed
Closed on 12/9/2023

**Comment by jayfey** [comment]
Use Case Description completed
Closed on 13/9/2023
