### ISSUE TITLE
2.3.2.1 Prepare slides for component diagram

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#20]
Task title ID: #2.3.2.1
Task description: Prepare slides for component diagram in preparation for M2 presentation
Goal: Complete slides for component diagram for use in M2 presentation
Success criteria: Slides completed and ready for use in M2 presentation
Allocated time: 4 Days
Start date: 24/10/2023
End date: 27/10/2023
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by jayfey** [comment]
Work Done description: Slides completed and ready for use in M2 presentation

Work committed to repo: No work committed to the repo

How does this work affect other work: Allows for use in M2 presentation

Start/End date: Ended on 24/10/2023, issue closed on 27/10/2023
