### ISSUE TITLE
2.4 Create Wireframe

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#21]
Task title ID: #2.4
Task description: Develop wireframe based on the requirements given
Goal: To create a wireframe containing all requirements
Success criteria: Wireframe contains all function requirements
Allocated time: 4 weeks
Start date: 29th August 2023
End date: 19th September 2023
Owner: Seth
Status: Completed
Priority:

**Comment by SethSIT** [comment]
Added the wireframes of the specific pages.
The HTML Pages will be developed according to the wireframes
Completed on 19th September, Started on 29th August
