### ISSUE TITLE
1.10 Create Project timeline

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#3]
Task title ID: #1.10
Task description: Create a Project timeline following SDLC, specifically planning, requirements gathering and design
Goal: Complete a that covers the entire project scope
Success criteria: Work is distributed appropriately from M1 to M3
Allocated time: 5 days
Start date: 31/08/23 
End date: 04/08/23
Owner: Zhen Yu
Status: Completed
Priority: High

**Comment by 2200877** [comment]
1. Finished Project Timeline
2. No commits
3. Does not affect other work
4. Started 31/08/23, Ended 19/09/23. Took too long as it was the first time doing this, and there was no lectures on this till week 4.
