### ISSUE TITLE
1.8.1 M1 Report: Introduction

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#31]
Task title ID: #1.8.1
Task description: Complete the introduction to the report. Find Details about the security industry and what requirements will be applicable to us, such as laws governing the scheduling of security officers. There should also be a general description of the document contents and any relevant required reading. 

Goal: The section should be guidance for any reader of the document who is not familiar with the domain of security work. There should be sufficient links to relevant articles that will further increase their knowledge. 

Success criteria: All Sections should be filled up and be relevant to the project. It should function as a good introduction to the report and domain for readers. 

Allocated time: 2 Days
Start date: 5th September
End date: 7th September
Owner: Naushad
Status: Completed. 
Priority: High

**Comment by NowShut** [comment]
Done with most of the requirements. 1.4 is pending if any new references are added to report.
