### ISSUE TITLE
1.8.2 M1 Report: Overall Description

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#32]
Task title ID: #1.8.2
Task description:
Goal:
Success criteria:
Allocated time:
Start date:
End date:
Owner: Seth
Status: Completed 2.1, 2.2, will start on 2.3 next week
Priority:

**Comment by SethSIT** [comment]
Completed the overall description on 14 September
Closed on 15/9/2023
