### ISSUE TITLE
1.8.3 M1 Report: Specific Requirements

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#33]
Task title ID: #1.8.3
Task description: Fill up the requirements of the project report, specifically the user interface requirements, functional requirements and non-functional requirements
Goal: Fill up all the requirements in the report 
Success criteria: All requirements from the client are added and any other necessary requirements are added
Allocated time: 5 days
Start date: 11/9/2023
End date: 14/9/2023
Owner: Darius
Status: In-Progress
Priority: Completed

**Comment by SethSIT** [comment]
Completed the UI requirements on 15th September

**Comment by Darius-Lim-zh** [comment]
Work Done description: All specific requirements completed with the help of Zhe yi, Naushad and Seth 

Work committed to repo: No work committed to the repo

How does this work affect other work: One part of the report is completed

Start/End date: Started on 29th August, ended and issue closed on 19/9/2023
