### ISSUE TITLE
1.3.1.4 M1 Report: Project estimation and Plan

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#34]
Task title ID: #1.3.1.4
Task description: Project Estimation and Plan in report
Goal: Finish the Project Estimation and Plan section in the report
Success criteria: Finished
Allocated time: 10 Days
Start date: 13/09/23
End date: 22/09/23
Owner: Zhen Yu
Status: Complete
Priority: Medium

**Comment by 2200877** [comment]
Finished Project Estimation and plan
No commits
Affects report, added some sections
Started 13/09/23, Ended 22/09/23
