### ISSUE TITLE
2.3.1.1 Update the report from M1 and add diagrams

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#36]
Task title ID: #2.3.1.1
Task description: Prepare the report for M2
Goal: Have report ready with all deliverables required
Success criteria: All headers are appropriately filled and all diagrams are inside
Allocated time: 4 Days
Start date: 23/10/2023
End date: 26/10/2023
Owner: Naushad 
Status: Completed
Priority: High

**Comment by NowShut** [comment]
Work Done description: M2 report is filled up with relevant updates from M1 Feedback. Required Diagrams added to M2.
Work committed to repo: No work committed to the repo. Updates made to M2 Report. 

How does this work affect other work: Relevant part of report is done. No Changes needed for other parts. 
Start/End date: Started on 23/10/2023, ended on 25/10/2023, issue closed on 29/10/2023
