### ISSUE TITLE
3.3.1 Prepare report for M3

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#39]
Task title ID: #3.3.1
Task description: Prepare the report for M3
Goal: Have report ready with all headers filled
Success criteria: All headers and deliverables are filled and fulfilled
Allocated time: 2 weeks
Start date: 10/11/23
End date: 24/11/23
Owner: Seth Teas
Status: Completed
Priority: High

**Comment by SethSIT** [comment]
Work Done description: Completed Report

Work committed to repo: No work committed to the repo. Diagram was added to M3 Report.

How does this work affect other work: Does not affect others.

Start/End date: Ended on 21/11/2023, issue closed on 21/11/2023
