### ISSUE TITLE
1.7 Create an activity diagram

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#4]
Task title ID: #1.7
Task description: Create the activity diagram to cover the workflow of all activities
Goal: Show the workflow of all activities
Success criteria: Activity diagram covers all possible activities
Allocated time: 4 weeks
Start date: 30/8/2023
End date:  19/9/2023
Owner: Ryan
Status: Completed
Priority: High

**Comment by LEEKWRYAN** [comment]
Finished initial draft based on initial requirements - Finished on 4/9/2023

Revised diagram after first meeting with client - Completed on 9/9/2023

Awaiting client's reply for further clarity on the requirements

**Comment by LEEKWRYAN** [comment]
Client replied to follow-up email on 13/9/2023, finalization of Activity diagram  in-progress

**Comment by LEEKWRYAN** [comment]
Activity Diagram completed on 19/9/2023
