### ISSUE TITLE
3.3.2 Prepare video for M3

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#40]
Task title ID: #3.3.2
Task description: Prepare the video for M3
Goal: Have video ready with all deliverables
Success criteria: All deliverables are addressed in the video
Allocated time: 2 Days
Start date: 21st November
End date: 22nd November
Owner: Naushad
Status:  Completed
Priority: Naushad

**Comment by NowShut** [comment]
Work Done description: Film and edit a walk-through of the prototype. 
Work committed to repo: No work committed to the repo. Video filmed and edited. 

How does this work affect other work: Does not affect others.

Start/End date: Ended on 21/11/2023, issue closed on 22/11/2023
