### ISSUE TITLE
1.8.3.1 M1 Report: User Interface Requirements

### ISSUE THREAD

**Issue by NowShut** [Darius-Lim-zh/INF2001P8-1#42]
Task title ID: #1.8.3.1
Task description: Convey the requirements of the user interface through the use of Wireframes accompanied by short description
Goal: Ensure all wireframes and descriptions are complete and accurate
Success criteria: Wireframes and descriptions are completed
Allocated time: 4 weeks
Start date: 29th August 2023
End date: 19th September 2023
Owner: Seth
Status: Completed
Priority: High

**Comment by SethSIT** [comment]
Work Done description: All aspects of UI are covered by wireframes with short descriptions

Work committed to repo: No work committed to the repo

How does this work affect other work: One part of the report for the specific requirements is complete. The wireframes can be used in a future task where making of the website is actually needed

Start/End date: Started on 29/8/2023, ended on 15/9/2023, issue closed on 19/9/2023
