### ISSUE TITLE
1.8.3.2 M1 Report: Functional Requirements

### ISSUE THREAD

**Issue by NowShut** [Darius-Lim-zh/INF2001P8-1#43]
Task title ID: #1.8.3.2
Task description: Fill up the functional requirements that were specified by the project description and the client during the client meeting
Goal: Ensure all functional requirements are filled 
Success criteria: All functional requirements specified by the project description and client are inputted
Allocated time: 5 days
Start date: 11/9/2023
End date: 14/9/2023
Owner: Darius
Status: Completed
Priority: High

**Comment by Darius-Lim-zh** [comment]
Work Done description: All functional requirements inputted

Work committed to repo: No work committed to the repo

How does this work affect other work: One part of the report for the specific requirements is complete

Start/End date: Started on 11/9/2023, ended and issue closed on 15/9/2023
