### ISSUE TITLE
1.3.1.3.3 Use Case Model

### ISSUE THREAD

**Issue by NowShut** [Darius-Lim-zh/INF2001P8-1#44]
Task title ID: #1.3.1.3.3
Task description:  Complete use case diagram and use case description
Goal: Complete use case diagram and use case description
Success criteria: Complete use case diagram and use case description
Allocated time: 2 days
Start date: 11/9/23
End date: 12/9/23
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by jayfey** [comment]
Work Done description: Completed use case model and added it into the report

Work committed to repo: No work committed to the repo

How does this work affect other work: Allows us to have a clearer view of the software, and allows for software estimation

Start/End date: Started on 11/9/23 Ended on 12/9/2023, issue closed on 23/9/2023
