### ISSUE TITLE
1.2.2.1 Pre Meeting Analysis

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#48]
Task title ID: #1.2.2.1
Task description: Analyse initial requirements given and determine questions that needs to be asked during client meeting
Goal: Come up with questions to ask in order to improve the initial requirements
Success criteria: Complete list of questions to be asked during client meeting
Allocated time: 1 week
Start date: 29/08/2023
End date: 03/09/2023
Owner: Ryan
Status: Completed
Priority: HIgh

**Comment by LEEKWRYAN** [comment]
Work Done description: Read through initial requirements and determined additional questions (functional and non-functional) that needed to be asked during meeting with client.
Work committed to repo: NIL.
Work affected: NIL.
Start date: 29/08/2023
End date: 03/09/2023
