### ISSUE TITLE
1.3.1 Prepare report for M1

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#5]
Task title ID: #1.3.1
Task description: Prepare the report with all headers filled for M1
Goal: Have the report detailed covering all necessary content
Success criteria: Each header properly detailed
Allocated time: 2 Days
Start date: 11th September
End date: 13th September
Owner: Naushad
Status: Completed
Priority: Medium

**Comment by NowShut** [comment]
Work Done description: All Relevant part of report filled. 

Work committed to repo: No work committed to the repo

How does this work affect other work: No Related Sections. Relevant part of report is done.
Start/End date: Started on 11/9/2023, ended on 13/9/2023, issue closed on 22/9/2023
