### ISSUE TITLE
1.2.2.2 Post Meeting Analysis

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#50]
Task title ID: #1.2.2.2
Task description: Requirements analysis after meeting with the client
Goal: Finalise and refine requirements according to client's feedback, determine additional questions to ask in follow-up email.
Success criteria:  Refined requirements cover all of client's feedback.
Allocated time: 5 days
Start date: 05/09/2023
End date: 10/09/2023
Owner: Ryan
Status: Completed
Priority: High

**Comment by LEEKWRYAN** [comment]
Work done description: Client meeting done online on 06/09/2023, refined and added requirements based on feedback given by client, determined additional questions to be asked in follow-up email.
Work committed to repo: NIL.
Affected work: M1 report: Functional & Non-Functional requirements, activity diagram, use case descriptions, use case diagram
Start date: 05/09/2023
End Date: 10/09/2023
