### ISSUE TITLE
3.2.1 Architecture design

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#52]
Task title ID: #3.2.1
Task description: Create an architecture diagram for the web application.
Goal: Show the architecture pattern chosen for the web application clearly.
Success criteria: Diagram Designed and added to M3 Report.
Allocated time:
Start date: 6th November
End date: 21st November
Owner: Naushad
Status: Completed
Priority: High

**Comment by NowShut** [comment]
Work Done description: Completed Architecture Design diagram and explanation. 

Work committed to repo: No work committed to the repo. Diagram was added to M3 Report. 

How does this work affect other work: Does not affect others. 

Start/End date: Ended on 6/11/2023, issue closed on 21/11/2023
