### ISSUE TITLE
1.3.1.1.1 Scope

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#54]
Task title ID: #1.3.1.1.1
Task description: Write out product scope specifying scope, boundaries, and purpose
Goal: Allow readers to understand product 
Success criteria: Understand and complete product scope
Allocated time: 3 days 
Start date: 15/9/2023
End date: 17/9/2023
Owner: Zhe Yi
Status: Completed
Priority: Medium

**Comment by jayfey** [comment]
Work Done description: Section has been filled and completed

Work committed to repo: No work committed to the repo

How does this work affect other work: Aid in understanding the need and requirements of the product to be designed
Start/End date: Started on 15/9/2023, ended on 17/9/2023, issue closed on 23/9/2023
