### ISSUE TITLE
1.3.1.1.2 Related Background

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#55]
Task title ID: #1.3.1.1.2
Task description: To research and find related background literature which can help us in better understanding the needs and requirements for the product
Goal: To better understand and aid in our product design
Success criteria: Research and complete background literature component in the report
Allocated time: 3 days
Start date: 15/9/2023
End date: 17/9/2023
Owner: Zhe Yi
Status: Completed
Priority: Medium

**Comment by jayfey** [comment]
Work Done description: Section has been completed and filled with relevant information and links 

Work committed to repo: No work committed to the repo

How does this work affect other work: Aids in identifying requirements and needs which affects design of our software (Relevant works include: Product functionality, Functionality requirement, etc.)
Start/End date: Started on 15/9/2023, ended on 17/9/2023, issue closed on 23/9/2023
