### ISSUE TITLE
1.3.1.1.3 Intended Audience

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#56]
Task title ID: #1.3.1.1.3
Task description: Complete the intended audience (1.5) section of Report M1.
Goal: Document a guide for any readers of M1 Report to orient themselves and also be informed of any relevant materials to refer to.
Success criteria: Section must be filled to sufficient level to allow any readers of document to be able to orient themselves.
Allocated time: 3 Days
Start date: 15th September
End date: 17th September
Owner: Naushad
Status: Completed
Priority: Low-Priority

**Comment by NowShut** [comment]
Work Done description: Section has been filled and all relevant links have also been attached. 

Work committed to repo: No work committed to the repo

How does this work affect other work: No Related Sections. Relevant part of report is done.
Start/End date: Started on 15/9/2023, ended on 17/9/2023, issue closed on 23/9/2023
