### ISSUE TITLE
1.3.1.1.4 Reference and Acknowledgements

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#57]
Task title ID: #1.3.1.1.4
Task description: Add References and Acknowledgements to M1.
Goal: Add References and acknowledgements to all sources that were useful in doing background research for the report M1.
Success criteria: All Relevant sources have been correctly acknowledged.
Allocated time: 3 days
Start date: 15th September
End date: 17th September
Owner: Naushad
Status: Completed
Priority: Low-Priority

**Comment by NowShut** [comment]
Work Done description: Section has been filled and all relevant links have also been attached.

Work committed to repo: No work committed to the repo

How does this work affect other work: No Related Sections. Relevant part of report is done.
Start/End date: Started on 15/9/2023, ended on 17/9/2023, issue closed on 23/9/2023
