### ISSUE TITLE
1.3.1.2.1 Product Overview

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#58]
Task title ID: #1.3.1.2.1
Task description: Provide an overview of the project
Goal: Ensure that the information written is clear so that people will understand what the project is about
Success criteria: The information written is clear and concise
Allocated time: 2 weeks
Start date: 29/8/23
End date: 15/9/23
Owner: Seth
Status: Complete
Priority: High

**Comment by SethSIT** [comment]
Work Done description: The information written is clear and concise

Work committed to repo: No work committed to the repo

How does this work affect other work: People will know what the project is about

Start/End date: Started on 29/8/2023, ended on 15/9/2023, issue closed on 23/9/2023
