### ISSUE TITLE
1.3.1.2.2 Product Functionality

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#59]
Task title ID: #1.3.1.2.2
Task description: Provide an overview of the key functions of the product
Goal: Ensure that the overview cover all aspects of the product
Success criteria: The overview is clear and cover every aspect of the product
Allocated time: 2 weeks
Start date: 29/8/23
End date: 15/8/23
Owner: Seth
Status: Complete
Priority: High

**Comment by SethSIT** [comment]
Work Done description: All product functionalities are covered and they are clear and can aid in future reference

Work committed to repo: No work committed to the repo

How does this work affect other work: We can refer back to the functionalities if needed during subsequent milestones

Start/End date: Started on 29/8/2023, ended on 15/9/2023, issue closed on 19/9/2023
