### ISSUE TITLE
1.3.1.4.1 Software Estimation

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#61]
Task title ID: #1.3.1.4.1
Task description: Section of Report
Goal: Finish the Software Estimation section of the report
Success criteria: UCP Calculated along with effort and project duration
Allocated time: 10 days
Start date: 13/09/23
End date: 22/09/23
Owner: Zhen Yu
Status: Complete
Priority: Low Priority

**Comment by 2200877** [comment]
Finished Project Timeline
No commits
Software Estimation Section in report finished
Started 13/09/23, Ended 22/09/23
