### ISSUE TITLE
1.3.1.4.2 Project Management

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#62]
Task title ID: #1.3.1.4.2
Task description: Section of Report
Goal: Finish the Project Management section of the report
Success criteria: Gantt Chart and WBS written in the report
Allocated time: 10 days
Start date: 13/09/23
End date: 22/09/23
Owner: Zhen Yu
Status: Complete
Priority: Low Priority

**Comment by 2200877** [comment]
Finished Project Timeline
No commits
Project Management Section in report finished
Started 13/09/23, Ended 22/09/23
