### ISSUE TITLE
2.2.2.1.1 Develop Controller classes

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#66]
Task title ID: #2.2.2.1.1
Task description: Determine what controller classes are needed in the system, as well as the operations/methods associated with them
Goal: Finalise controller classes and the methods
Success criteria: Completed controller classes and the methods
Allocated time: 5 days
Start date: 08/10/2023
End date: 13/10/2023
Owner: Ryan
Status: In-Progress
Priority: High

**Comment by LEEKWRYAN** [comment]
Completed first draft of controller classes - 13/10/2023

**Comment by LEEKWRYAN** [comment]
Work Done description: Finalised Controller classes, including the required functions
Work committed to repo: NIL.
How does this work affect other work: Class diagram
Start date: 08/10/2023
End date: 15/10/2023
