### ISSUE TITLE
2.2.2.2.1 Staff Sequence Diagram: Indicate availability & preference

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#69]
Task title ID: #2.2.2.2.1
Task description: Develop the staff sequence diagram for the use case indicate availability and preference
Goal: Create the sequence diagram for the use case indicate availability and preference
Success criteria: Have the sequence diagram created with all requirements fulfilled
Allocated time: 5 days
Start date: 13/10/2023
End date: 19/10/2023
Owner: Naushad
Status: Completed
Priority: High

**Comment by NowShut** [comment]
Work Done description: Sequence Diagram Created For Indicating Availability and Preference
Work committed to repo: No work committed to the repo. Diagram Added to Report.

How does this work affect other work: No Related Sections. Diagram Added to relevant section of M2.
Start/End date: Started on 13/10/2023, ended on 19/10/2023, issue closed on 23/10/2023
