### ISSUE TITLE
2.2.2.2.2 Manager Sequence Diagram: Manage jobs

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#70]
Task title ID: #2.2.2.2.2
Task description: Create a sequence diagram for the use case where Manager allocates jobs for the staff
Goal: Develop the sequence diagram with correct annotations
Success criteria: Complete sequence diagram
Allocated time: 7 days
Start date: 13/10/2023
End date: 19/10/2023
Owner: Seth
Status: Completed
Priority: High

**Comment by SethSIT** [comment]
Work Done description: Update the sequence diagram with the correct allocations

Work committed to repo: No work committed to the repo

How does this work affect other work: The diagram can be referred to when needed

Start/End date: Started on 18/10/2023, ended on 18/10/2023, issue closed on 18/10/2023
