### ISSUE TITLE
2.2.2.2.3.2 IT Administrator Sequence Diagram: Manage Accounts

### ISSUE THREAD

**Issue by LEEKWRYAN** [Darius-Lim-zh/INF2001P8-1#71]
Task title ID: #2.2.2.2.3.2
Task description: Add a sequence diagram to illustrate the managing of accounts, including editing accounts and deleting accounts
Goal: Construct the diagram according to the steps in the managing accounts use case
Success criteria: Diagram is done correctly and accurately
Allocated time: 1 week
Start date: 17th October 2023
End date: 24th October 2023
Owner: Seth Teas
Status: Completed
Priority: High

**Comment by SethSIT** [comment]
Work Done description: Sequence diagram is done according to the use case

Work committed to repo: No work committed to the repo

How does this work affect other work: It illustrates the process of editing and deleting user accounts and may be needed in case we are unsure how the process will be implemented

Start/End date: Started on 17/10/2023, ended on 17/10/2023, closed on 17/10/2023
