### ISSUE TITLE
2.2.1.1.1 Develop and connect components

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#81]
Task title ID: #2.2.1.1.1
Task description:  To design the component diagram according to product requirement and class diagram.
Goal: To complete the component diagram according to product requirement and class diagram
Success criteria:  Completed component diagram that shows each component and the interactions between components
Allocated time: 6 Days
Start date: 17/10/2023
End date: 22/10/2023
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by jayfey** [comment]
Work Done description: Designed the component diagram according to product requirement and  class diagram

Work committed to repo: No work committed to the repo

How does this work affect other work: Allows for refinement of class diagram and clearer understanding of product overview

Start/End date: Ended on 17/10/2023, issue closed on 22/10/2023
