### ISSUE TITLE
2.2.1.1.2 Reflect components onto ECB

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#82]
Task title ID: #2.2.1.1.2
Task description: Reflect components onto ECB
Goal: Add components to ECB
Success criteria: Components added to ECB
Allocated time: 6 Days
Start date: 17/10/23
End date: 22/12/23
Owner: Zhen Yu
Status: Complete
Priority: High

**Comment by 2200877** [comment]
Finished Reflect components onto ECB
No commits
Affects Class Diagram, Component Diagram
Started 17/10/23, ended 22/10/23
