### ISSUE TITLE
2.3.2.2 Prepare slides for class and sequence diagram

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#83]
Task title ID: #2.3.2.2
Task description: Create slides for M2 presentation
Goal: Create presentation slides for M2, especially for class and sequence diagram
Success criteria: Finish creation of presentation slides
Allocated time: 22 days
Start date: 06/10/2023
End date: 27/10/2023
Owner: Ryan and Zhe Yi
Status: In-Progress
Priority: High

**Comment by LEEKWRYAN** [comment]
Work Done description: Finished creating slides for M2 presentation
Work committed to repo: NIL.
How does this work affect other work: NIL.
Start date: 06/10/2023
End date: 27/10/2023
