### ISSUE TITLE
3.2.2.1 First Design Pattern

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#84]
Task title ID: #3.2.2.1
Task description: Decide on a possible design pattern to inplement on one of the prominent functions
Goal: Implement the design pattern into the class diagram
Success criteria: Decide and justify which design pattern to implement, as well as make changes to the class diagram to include the design pattern.
Allocated time: 6 days
Start date: 12/11/2023
End date: 19/11/2023
Owner: Ryan
Status: Completed
Priority: High

**Comment by LEEKWRYAN** [comment]
Work Done description: Decided on first design pattern, provided justification and changed class diagram to show the implemented pattern.
Work committed to repo: NIL.
How does this work affect other work: Completion of M3 report
Start date: 12/11/2023
End date: 19/11/2023
