### ISSUE TITLE
3.2.3.2 White box testing

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#87]
Task title ID: #3.2.3.2
Task description: Complete white box testing 
Goal: Complete white box testing
Success criteria: White box testing completed with all relevant components done such as paths
Allocated time: 7 Days
Start date: 3/11/2023
End date: 9/11/2023
Owner: Zhe Yi
Status: Completed
Priority: High

**Comment by iissteadyone** [comment]
Work Done description: Calculated and completed white box testing
Work committed to repo: No work committed to the repo. White box testing added to report
How does this work affect other work: Does not affect others.

Start/End date: Ended on 3/11/2023, issue closed on 9/11/2023
