### ISSUE TITLE
3.2.4 Wireframe

### ISSUE THREAD

**Issue by Darius-Lim-zh** [Darius-Lim-zh/INF2001P8-1#88]
Task title ID: #3.2.4
Task description: Update the M3 Report with the wireframes in section 4
Goal: Each Wireframe must be accompanied with the scenario and functional requirements and use case
Success criteria: All are updated accurately and comprehensively
Allocated time: 4 weeks
Start date: 31/10/23
End date: 25/11/23
Owner: Seth Teas
Status: Completed
Priority: High

**Comment by SethSIT** [comment]
Work Done description: Update M3 Report with the wireframes accompanied by the use cases, functional requirements and scenarios

Work committed to repo: No work committed to the repo

How does this work affect other work: The diagrams can aid in M3 Presentation

Start/End date: Started on 31/10/2023, ended on 25/11/2023, issue closed on 01/11/2023
